- hosts: all
  roles:
    - role: fetch-refstack-subunit-output
      vars:
        zuul_work_dir: "{{ ansible_user }}/{{ zuul.projet.src_dir }}/.tempest"
        #        fetch_subunit_output_additional_dirs:
        #  - "{{ zuul.project.src_dir }}/.tempest"
