---
- name: Fetch tarball from the pod
  command: >
    oc --context "{{ zj_pod.1.context }}"
       --namespace "{{ zj_pod.1.namespace }}"
        rsync -q --progress=false
          {{ zj_pod.1.pod }}:{{ zj_output.src }}/
          {{ zj_output.dst }}/
  no_log: "{{ not zuul_log_verbose }}"
  delegate_to: localhost
  loop:
    - src: "{{ ansible_collection_build_collection_tarball }}"
      dst: "{{ ansible_collection_build_artifact_path }}"
  loop_control:
    loop_var: zj_output
