- name: Find subunit2html
  include: find-subunit-html.yaml

- name: Generate testr_results.html file
  command: "{{ subunit_html_command }} ./testrepository.subunit testr_results.html"
  args:
    chdir: "{{ zuul_work_dir }}"
  when: subunit_html_command is defined

- name: Find subunit files
  find:
    paths:
      - "{{ zuul_work_dir }}"
    patterns:
      - testr_results.html
      - testrepository.subunit
      - alerts.csv
  register: subunit_files

- name: Collect test-results
  synchronize:
    dest: "{{ zuul.executor.log_root }}"
    mode: pull
    src: "{{ zj_item.path }}"
    verify_host: true
    group: no
    owner: no
  loop: "{{ subunit_files.files }}"
  loop_control:
    loop_var: zj_item

- name: Return artifact to Zuul
  zuul_return:
    data:
      zuul:
        artifacts:
          - name: "Unit Test Report"
            url: "testr_results.html"
            metadata:
              type: unit_test_report
  when: "'testr_results.html' in zj_item.path"
  loop: "{{ subunit_files.files }}"
  loop_control:
    loop_var: zj_item
