---
- name: Ensure artifacts directory exists
  file:
    path: "{{ goreleaser_artifact_path }}"
    state: directory
  delegate_to: localhost

- name: Collect tarball artifacts
  synchronize:
    dest: "{{ goreleaser_artifact_path }}"
    mode: pull
    src: "{{ zj_tb }}"
    verify_host: true
    owner: false
    group: false
  loop: "{{ goreleaser_tarballs }}"
  loop_control:
    loop_var: zj_tb
  when: "ansible_connection != 'kubectl'"

- include_tasks: rsync.yaml
  when:
    - zj_pod.1.pod is defined
    - ansible_connection == 'kubectl'
  loop: "{{ openshift_pods.items()|list }}"
  loop_control:
    loop_var: zj_pod
  run_once: true

- name: Return collection artifacts to Zuul
  zuul_return:
    data:
      zuul:
        artifacts:
          - name:
              "{% set x = zj_tb | basename | replace('.tar.gz', '') %}{{ x.split('_')[0] }}"
            url: "artifacts/{{ zj_tb | basename }}"
            metadata:
              type: go_binary_archive
              version: "{% set x = zj_tb | basename | replace('.tar.gz', '') %}{{ x.split('_')[1] }}"
              platform: "{% set x = zj_tb | basename | replace('.tar.gz', '') %}{{ x.split('_')[2] }}"
  loop: "{{ goreleaser_tarballs }}"
  loop_control:
    loop_var: zj_tb
