---
- name: Initialize terraform
  command: "{{ terraform_executable }} init -no-color -input=false"
  args:
    chdir: "{{ zuul_work_dir }}"

- name: Run terraform fmt
  command: "{{ terraform_executable }} fmt -check -recursive"

- name: Run terraform validate
  command: "{{ terraform_executable }} validate"
