---
zuul_work_dir: "{{ zuul.project.src_dir }}"
ansible_collection_build_galaxy_executable: "{{ ansible_collection_build_pip_virtualenv }}/bin/ansible-galaxy"
ansible_collection_build_galaxy_output_path: "build_artifacts"
ansible_collection_build_artifact_path: "{{ zuul.executor.log_root }}/artifacts/"
ansible_collection_build_collection_verify: true
ansible_collection_build_generate_version: true
ansible_collection_build_save_artifact: true
ansible_collection_build_pip_dependencies:
  # - galaxy_importer
  - ruamel.yaml
  - pbr
ansible_collection_build_pip_virtualenv: "{{ ansible_user_dir }}/.local/venv"
ansible_collection_build_pip_extra_args:
