---
- name: Generate Dockerfile
  template:
    src: "Dockerfile.j2"
    dest: "{{ zuul_work_dir }}/Dockerfile"

- name: List files
  command: "ls -l"
  args:
    chdir: "{{ zuul_work_dir }}"
  register: ls
- name: Log current files which will be written to the image
  debug:
    var: ls.stdout_lines

- name: Prepare test image
  command: "docker build -qt {{ simple_image_name }} ."
  args:
    chdir: "{{ zuul_work_dir }}"

- name: Run with cleanup
  block:
  - name: Run the image
    command: "docker run --rm --privileged {{ simple_image_name }}"
    args:
      chdir: "{{ zuul_work_dir }}"
    register: container_result
  - name: Log test log
    debug:
      msg: "{{ container_result.stdout_lines }}"
  always:
  - name: Remove used image
    command: "docker rmi {{ simple_image_name }}"
