---
- name: Generate Dockerfile
  template:
    src: "Dockerfile.j2"
    dest: "./Dockerfile"

- name: Prepare test image
  command: "docker build -qt {{ simple_image_name }} ."

- name: Run with cleanup
  block:
  - name: Run the image
    command: "docker run --rm --privileged {{ simple_image_name }}"
    register: container_result
  - name: Log test log
    debug:
      msg: "{{ container_result.stdout_lines }}"
  always:
  - name: Remove used image
    command: "docker rmi {{ simple_image_name }}"
