---
goreleaser_project_src_dir: "{{ ansible_user_dir }}/{{ zuul.project.src_dir }}"
goreleaser_dist_path: "{{ goreleaser_project_src_dir }}/dist"
goreleaser_artifact_path: "{{ zuul.executor.log_root }}/artifacts/"
goreleaser_save_artifact: true
goreleaser_sign: false
gpg_key:
  private:
goreleaser_args: "--snapshot --rm-dist"
